apiVersion: apps/v1
kind: Deployment
metadata:
  name: smos-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smos-backend
  template:
    metadata:
      labels:
        app: smos-backend
    spec:
      containers:
      - name: smos-backend
        image: gcr.io/GEN_LANG_CLIENT_ID_PLACEHOLDER/smos-backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: smos-config
        - secretRef:
            name: smos-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: smos-backend-service
spec:
  selector:
    app: smos-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer