apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: smos-criu-runtime
handler: runsc
# Enabling pod checkpointing and restoration for GKE.
# This handler is associated with gVisor/CRIU support.
scheduling:
  nodeSelector:
    runtime: criu-enabled