apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: gvisor
  annotations:
    io.kubernetes.cri-o.CheckpointRestore: "true" # Required for CRIU integration in supported environments
handler: runsc

