apiVersion: v1
kind: Service
metadata:
  name: smos-agents-svc
  labels:
    app: smos
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: smos
    component: agents
